name:                FunctionalProgrammingLab4
version:             0.1.0.0
github:              "githubuser/FunctionalProgrammingLab4"
license:             BSD-3-Clause
author:              "antonvedaet"
maintainer:          "example@example.com"
copyright:           "2024 antonvedaet"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/FunctionalProgrammingLab4#readme>

dependencies:
- base >= 4.7 && < 5
- free
- text
- HUnit >=1.6.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  FunctionalProgrammingLab4-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunctionalProgrammingLab4

tests:
  FunctionalProgrammingLab4-test:
    main:                test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunctionalProgrammingLab4
